# Generated by Django 4.0.3 on 2022-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_rename_result_irisdata_prediction_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irisdata',
            name='date',
        ),
        migrations.AddField(
            model_name='irisdata',
            name='date_time',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
